### ISSUE TITLE
Crash when calling attest

### ISSUE THREAD

**Issue by nfacha** [mofneko/Lilium#6]
```
02-15 11:22:42.755 23880  6438 E Unity   : AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/collection/ArraySet;
02-15 11:22:42.755 23880  6438 E Unity   : java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/collection/ArraySet;
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.google.android.gms.common.api.internal.GoogleApiManager.<init>(Unknown Source:29)
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.google.android.gms.common.api.internal.GoogleApiManager.zab(Unknown Source:8)
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:44)
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:53)
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.google.android.gms.safetynet.SafetyNetClient.<init>(Unknown Source:8)
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.google.android.gms.safetynet.SafetyNet.getClient(Unknown Source:2)
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.nekolaboratory.Lilium.d.a(Unknown Source:24)
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.nekolaboratory.Lilium.b.a(Unknown Source:22)
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.nekolaboratory.Lilium.b.a(Unknown Source:24)
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.nekolaboratory.Lilium.b.a(Unknown Source:90)
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.nekolaboratory.Lilium.Lilium.attest(Unknown Source:12)
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.nekolaboratory.Lilium.Lilium.attest(Unknown Source:6)
02-15 11:22:42.755 23880  6438 E Unity   : 	at com.unity3d.p
```

**Comment by nfacha** [comment]
Fixed by adding the following custom Gradle properties:
```
android.enableJetifier=true
android.useAndroidX=true
```
